before_script:
  - php composer.phar -n -q install
  - cp ~/Config.php src/snac/Config.php
  - rm -rf ~/public_html/snac_server
  - ln -s `pwd`/src/virtualhosts ~/public_html/snac_server

stages:
  - test
  - documentation

run_test:
  script:
    - vendor/bin/phpunit --coverage-text --colors=never
  stage: test
  only:
    - development

generate_docs:
  script:
    - vendor/bin/phpdoc -d src/ -t doc/ -i src/snac/Config.php --template="responsive-twig" --title="SNAC Programming API" --validate --defaultpackagename="snac_server" --force
    - rsync -av doc/ /projects/snac_server/doc/
  stage: documentation
  only:
    - development
